baseURL = "https://kondor6c.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Web Book"
theme = [ "mainroad" ]
themesdir = "themes/"
paginate = "10"
hasCJKLanguage = false
publishDir = "kondor6c.github.io"
enableEmoji = false
pygmentsStyle = "tango"
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
[outputs]
home = [ "HTML", "RSS"]

[deployment]
order = [".jpg$", ".gif$"]
[[deployment.targets]]
name = "github"

[[deployment.targets]]
name = "github"

[params]
author = "Kevin Faulkner"
copyright = "Kevin Faulkner"
description = "simple helpful log of information"
disableLanguageSwitchingButton = true
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
editURL = "https://github.com/kondor6c/blog"
enableGitInfo = true
opengraph = false
twitter_cards = false
ordersectionsby = "weight" # ordersectionsby = "title"
themeVariant = "blue"
[Params.widgets.social]
telegram = "kondor6c"
github = "kondor6c"
gitlab = "kondor6c"
bitbucket = "kondor6c"
email = "kondor6c@lazytree.us"

[Params.logo]
image = "static/images/tux_logo.png"
[Params.sidebar]
home = "right" # Configure layout for home page
list = "left"  # Configure layout for list pages
single = false 
widgets = ["search", "recent", "categories", "taglist", "social"]


[[menu.shortcuts]]
name = "Main"
url = "/"
weight = 2
[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30



